version: '3.9'

services:
    web:
        build:
            context: ./
            dockerfile: Dockerfile
        command: pdm run python3 main.py
        expose:
            - 8000
        ports:
            - "8000:8000"
        networks:
            - backend

networks:
  backend:
